### PR TITLE
add option in ntiles_n for probabilities

### PR DESCRIPTION
**Pull request by yonicd**
i was going for this output since most of the time users would want to pass critical values to see the tails.

```r
ggplot(iris, aes(x=Sepal.Length, y=Species, fill=factor(..ntile..))) + 
geom_joy_gradient(calc_ecdf = TRUE, ntiles_n = c(0.05,0.95))
```

image

### CODE REVIEW

**Comment by clauswilke** [comment]
This is fine in principle. A couple of comments and requests, though:

1. Please document this new feature in the `@param` section of `stat_joy()`.
2. With this option, the name `ntiles_n` is probably misleading. I think simply `ntiles` or `quantiles` would be more appropriate.
3. **Important:** I just committed an important bug fix related to missing `ntiles_n` arguments in `geom_joy()`. Please do a git pull before you change the name of `ntiles_n`.

**Comment by yonicd** [comment]
i noticed that too (i made my own patch that is just like yours), i'll pull again. cleaned up the code a bit and added another check that user put in vector in [0,1]

**Comment by clauswilke** [comment]
FYI, I made extensive cleanups to your code. I care a lot about consistent spacing etc. Also, I renamed the aesthetic from `ntile` to `quantile` which fits better with the parameter `quantiles`. So make sure you map to `..quantile..` in the future.

Thanks!

**Comment by yonicd** [comment]
Thanks for adding the PR, hopefully it will get used ;)

**Pull request merged**
