### PR TITLE
Removed purrr depency, reduced minimum R version

### PR DESCRIPTION
**Pull request by jonathon-love**

### CODE REVIEW

**Comment by clauswilke** [comment]
Could you add a few sentences of documentation/comments for the `reduce` function you added, and also a few unit tests in `tests/testthat`? Thanks!

**Comment by clauswilke** [comment]
There also was a CRAN check fail on Travis.

**Comment by clauswilke** [comment]
Your patch seems to be passing CRAN check now.

**Comment by jonathon-love** [comment]
Ok, should be good to go

**Comment by clauswilke** [comment]
Thanks!

**Comment by jonathon-love** [comment]
np

**Pull request merged**
